version: "3.7"
services:
  web:
    image: abiosoft/caddy
    environment:
      - ACME_AGREE=true
      - BOT_DOMAIN
      - ACME_EMAIL
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./caddy/:/root/.caddy:rw
    ports:
      - 80:80
      - 443:443
  app:
    build: .
    env_file:
      - .env
    environment:
      - BAMBOOHR_COMPANY
      - SLACK_TOKEN
    volumes:
      - database.json:/app/database.json
    ports:
      - 9000:9000
